DollarTime/config/routes.rb
Rails.application.routes.draw do
  resources :incomelogs
  root 'greetings#hello'
  get '/user', to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#	get '/welcome'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

DollarTime/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DollarTime/app/models/incomelog.rb
class Incomelog < ApplicationRecord
  belongs_to :user, optional: true
end

DollarTime/app/models/user.rb
class User < ApplicationRecord
  has_many :incomelogs 
 # def self.from_omniauth(auth)
 #   where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
 #     user.provider = auth.provider
 #     user.uid = auth.uid
 #     user.name = auth.info.name
 #     user.oauth_token = auth.credentials.token
 #     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
 #     user.save!
 #   end
 # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
      end
    end




end

DollarTime/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def current_user
	  @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

DollarTime/app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
    @currentTime = Time.now
  end
 

end

DollarTime/app/controllers/incomelogs_controller.rb
class IncomelogsController < ApplicationController
  before_action :set_incomelog, only: [:show, :edit, :update, :destroy]

  # GET /incomelogs
  # GET /incomelogs.json
  def index
    @incomelogs = Incomelog.all
  end

  # GET /incomelogs/1
  # GET /incomelogs/1.json
  def show
  end

  # GET /incomelogs/new
  def new
    @incomelog = Incomelog.new

  end

  # GET /incomelogs/1/edit
  def edit
  end

  # POST /incomelogs
  # POST /incomelogs.json
  def create
    @incomelog = Incomelog.new(incomelog_params)

    respond_to do |format|
      if @incomelog.save
        format.html { redirect_to @incomelog, notice: 'Incomelog was successfully created.' }
        format.json { render :show, status: :created, location: @incomelog }
      else
        format.html { render :new }
        format.json { render json: @incomelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomelogs/1
  # PATCH/PUT /incomelogs/1.json
  def update
    respond_to do |format|
      if @incomelog.update(incomelog_params)
        format.html { redirect_to @incomelog, notice: 'Incomelog was successfully updated.' }
        format.json { render :show, status: :ok, location: @incomelog }
      else
        format.html { render :edit }
        format.json { render json: @incomelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomelogs/1
  # DELETE /incomelogs/1.json
  def destroy
    @incomelog.destroy
    respond_to do |format|
      format.html { redirect_to incomelogs_url, notice: 'Incomelog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incomelog
      @incomelog = Incomelog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incomelog_params
      params.require(:incomelog).permit(:user_id, :job, :amount)
    end
end

DollarTime/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

DollarTime/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.all 
  end
  

end

DollarTime/app/helpers/application_helper.rb
module ApplicationHelper
end

DollarTime/app/helpers/greetings_helper.rb
module GreetingsHelper
end

DollarTime/app/helpers/incomelogs_helper.rb
module IncomelogsHelper
end

DollarTime/app/helpers/sessions_helper.rb
module SessionsHelper
end

DollarTime/app/views/greetings/hello.html.erb
<html>
<h1>DollarTime</h1>
<body>
<script>
  window.onload = function () {

  var seconds = 00;
  var tens = 00;
  var appendTens = document.getElementById("tens")
  var appendSeconds = document.getElementById("seconds")
  var buttonStart = document.getElementById('button-start');
  var buttonStop = document.getElementById('button-stop');
  var buttonReset = document.getElementById('button-reset');
  var Interval ;

  buttonStart.onclick = function() {

  clearInterval(Interval);
  Interval = setInterval(startTimer, 10);
  }

  buttonStop.onclick = function() {
  clearInterval(Interval);
  }


  buttonReset.onclick = function() {
  clearInterval(Interval);
  tens = "00";
  seconds = "00";
  appendTens.innerHTML = tens;
  appendSeconds.innerHTML = seconds;
  }



  function startTimer () {
  tens++;

  if(tens < 9){
	    appendTens.innerHTML = "0" + tens;
	    }

	    if (tens > 9){
    appendTens.innerHTML = tens;

    }

    if (tens > 99) {
    console.log("seconds");
    seconds++;
    appendSeconds.innerHTML = "0" + seconds;
    tens = 0;
    appendTens.innerHTML = "0" + 0;
    }

    if (seconds > 9){
    appendSeconds.innerHTML = seconds;
    }

    }


    }
</script>
<p>Hope everybody is doing well!!     Happy Hacking!!!</p>
<br>
<div class="wrapper">
  <h1>Let it Rain</h1>
  <p><span id="seconds">00</span>:<span id="tens">00</span></p>
  <button id="button-start">Start</button>
  <button id="button-stop">Stop</button>
  <button id="button-reset">Reset</button>
  </div> 
<p>Please Log in using facebook account</p>
<a href = "http://168.122.130.109:3000/incomelogs">Check out your income history</a>
</body>
</html>

<style>

html{
	text-align: center; 
}
/* Variabes */
$orange: #ffa600;
$grey:#f3f3f3;
$white: #fff;
$base-color:$orange ;


/* Mixin's */
@mixin transition {
-webkit-transition: all 0.5s ease-in-out;
-moz-transition: all 0.5s ease-in-out;
transition: all 0.5s ease-in-out;
}
@mixin corners ($radius) {
-moz-border-radius: $radius;
-webkit-border-radius: $radius;
border-radius: $radius;
-khtml-border-radius: $radius;
}

body {
background:$base-color;
font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
height:100%;
}

.wrapper {
width: 800px;
margin: 30px auto;
color:$white;
text-align:center;
}

h1, h2, h3 {
font-family: 'Roboto', sans-serif;
font-weight: 100;
font-size: 2.6em;
text-transform: uppercase;
}

#seconds, #tens{
font-size:2em;
}

button{
@include corners (5px);
background:$base-color;
color:$white;
border: solid 1px $white;
text-decoration:none;
cursor:pointer;
font-size:1.2em;
padding:18px 10px;
width:180px;
margin: 10px;
outline: none;
&:hover{
@include transition;
background:$white;
border: solid 1px $white;
color:$base-color;
}
}

</style>

DollarTime/app/views/greetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><%= user.uid %></td>
      <td><%= user.name %></td>
    </tr>
    <% end %>
  </tbody>
  </table>

DollarTime/app/views/incomelogs/_form.html.erb
<%= form_for(incomelog) do |f| %>
  <% if incomelog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(incomelog.errors.count, "error") %> prohibited this incomelog from being saved:</h2>

      <ul>
      <% incomelog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :job %>
    <%= f.text_field :job %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

DollarTime/app/views/incomelogs/edit.html.erb
<h1>Editing Incomelog</h1>

<%= render 'form', incomelog: @incomelog %>

<%= link_to 'Show', @incomelog %> |
<%= link_to 'Back', incomelogs_path %>

DollarTime/app/views/incomelogs/index.html.erb
<html>
<p id="notice"><%= notice %></p>

<h1>Income Hisoty Log</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Job</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomelogs.each do |incomelog| %>
      <tr>
        <td><%= incomelog.user_id %></td>
        <td><%= incomelog.job %></td>
        <td><%= incomelog.amount %></td>
        <td><%= link_to 'Show', incomelog %></td>
        <td><%= link_to 'Edit', edit_incomelog_path(incomelog) %></td>
        <td><%= link_to 'Destroy', incomelog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incomelog', new_incomelog_path %>
<%= link_to 'Home Page', root_url %>
</html>
<style>
html{
	text-align: center;
}
</style>

DollarTime/app/views/incomelogs/new.html.erb
<h1>New Incomelog</h1>

<%= render 'form', incomelog: @incomelog %>

<%= link_to 'Back', incomelogs_path %>

DollarTime/app/views/incomelogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @incomelog.user_id %>
</p>

<p>
  <strong>Job:</strong>
  <%= @incomelog.job %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @incomelog.amount %>
</p>

<%= link_to 'Edit', edit_incomelog_path(@incomelog) %> |
<%= link_to 'Back', incomelogs_path %>

DollarTime/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DollarTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user-widget">
      <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>

DollarTime/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><%= user.uid %></td>
      <td><%= user.name %></td>
    </tr>
    <% end %>
  </tbody>
  </table>